pipeline {
    agent any

    stages {
        stage('Clonar repositorio principal') {
            steps {
                script {
                    dir('repo-principal') {
                        git branch: 'develop', url: 'https://github.com/stemdo-labs/iac-ibmcloud-aitorcajas.git'
                    }
                }
            }
        }

        stage('Cargar y Ejecutar Pipeline Común') {
            steps {
                script {
                    def environment = load 'repo-principal/vars/environment.groovy'
                    environment.pipeline()
                }
            }
        }

        stage('Prueba de variables de entorno') {
            steps {
                script {
                    echo "Entorno definido: ${env.ENVIRONMENT}"
                }
            }
        }
    }
}
