pipeline {
    agent any

    stages {
        stage('Cargar y Ejecutar Pipeline Común') {
            steps {
                script {
                    def pipelineTemplate = load 'stemdo-labs/iac-ibmcloud-aitorcajas/vars/environmentPipeline.groovy'
                    pipelineTemplate.call()
                }
            }
        }
    }
}
