pipeline {
    agent any

    stages {
        stage('Clonar repositorio principal') {
            steps {
                script {
                    dir('repo-principal') {
                        git branch: 'develop', url: 'https://github.com/stemdo-labs/iac-ibmcloud-aitorcajas.git'
                    }
                }
            }
        }

        stage('Verificar archivo Groovy') {
            steps {
                script {
                    sh 'cat repo-principal/vars/environmentPipeline.groovy'
                }
            }
        }

        stage('Cargar y Ejecutar Pipeline Común') {
            steps {
                script {
                    def environment = load 'repo-principal/vars/environmentPipeline.groovy'
                    environment.ejecutarPipeline()
                }
            }
        }
    }
}
