name: CI-CD backend && SonarQube

on:
  workflow_dispatch:

jobs:
  environment:
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/environment.yml@main

  build:
    needs: environment
    name: Build and analyze
    runs-on: ubuntu-latest
    environment: ${{ needs.environment.outputs.entorno }}
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      project_key: ${{ steps.project_key.outputs.KEY }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extraer versión
        id: version
        run: |
          VERSION=$(grep -oP '<version>\K[^\<]+' pom.xml | sed -n '2p')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Extraer projectKey
        id: project_key
        run: |
          KEY=$(grep -oP '^sonar.projectKey=\K.*' sonar-project.properties)
          echo "KEY=$KEY" >> $GITHUB_OUTPUT

  sonar:
    needs: [environment, build]
    uses: stemdo-labs/S-SDLC_SonarQube/.github/workflows/sonarqube-analysis.yml@acajas-branch
    with:
      version: ${{ needs.build.outputs.version }}
      project_key: ${{ needs.build.outputs.project_key }}
      entorno: ${{ needs.environment.outputs.entorno }}
    secrets: inherit

  ci:
    needs: [environment, sonar]
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/ci.yml@main
    with:
      entorno: ${{ needs.environment.outputs.entorno }}
      desarrollo: ${{ needs.environment.outputs.desarrollo }}
    secrets: inherit

  cd:
    needs: [ci, environment]
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/cd.yml@main
    with:
      desarrollo: ${{ needs.environment.outputs.desarrollo }}
      entorno: ${{ needs.environment.outputs.entorno }}
    secrets: inherit