name: Buildear imagen del backend

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main

jobs:
  ci:
    uses: stemdo-labs/final-project-exercise-aitorcajas/.github/workflows/ci.yml@main
    secrets: inherit

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Mostrar versión del backend
        run: echo "{{ needs.ci.outputs.app_desarrollo }}"